spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8082
enreka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
jpa:
  show-sql: true
  properties:
    hibernate.format_sql: true #格式化sql